module.exports = [
  ["chat", "chien"],
  ["pizza", "burger"],
  ["voiture", "moto"],
  ["soleil", "lune"],
  ["paris", "londres"],
  ["football", "basket"],
  ["eau", "feu"],
  ["pain", "croissant"],
  ["avion", "bateau"],
  ["roi", "empereur"],
  ["café", "thé"],
  ["école", "université"],
  ["guitare", "piano"],
  ["montagne", "mer"],
  ["ninja", "samurai"],
  ["dragon", "licorne"],
  ["iphone", "android"],
  ["tiktok", "instagram"],
  ["youtube", "twitch"],
  ["soleil", "étoile"],
];